### ISSUE TITLE
Support HTTPS/SSL

### ISSUE THREAD

**Issue by RDIL** [paramt/1pt#7]
https 👏 is 👏 the 👏 future 👏

**Comment by paramt** [comment]
I've been attempting to install an SSL certifcate for quite a while now but it's not working out... I might try some hacky 'proxy' solution, but in the meantime there's always the unofficial HTTPS endpoint :P

https://thakkaha.dev.fast.sheridanc.on.ca/pme/1pt/add-url-to-db.php

**Comment by paramt** [comment]
### Update
I'll be moving the API over to [Zeit](https://zeit.co) in the next few weeks, which should hopefully resolve this issue 🤞

**Comment by paramt** [comment]
Resolved with 8b46bb64eddab6b6b3e474a953ecdc0e9aa394ac, [the endpoint](https://api.1pt.co) now supports SSL
